workflows:
  android-workflow:
    name: Algol Client Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      java: 17
      vars:
        PACKAGE_NAME: "com.algol.client"
    scripts:
      - name: Set up local.properties
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android Debug APK
        script: | 
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - build@codemagic.io
        notify:
          success: true
          failure: false
